# Generated by Django 5.1.2 on 2024-10-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_deposit_transfer_withdraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
