# Generated by Django 5.1.2 on 2024-10-24 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_branch_options_remove_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='branch',
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_branch',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='api.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='api.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
