# Generated by Django 5.1.2 on 2024-10-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
    ]
