# Generated by Django 5.1.2 on 2024-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transfer_branch_transfer_from_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientManager',
        ),
    ]
