# Generated by Django 5.1.2 on 2024-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_clientmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.ManyToManyField(related_name='banks', to='api.branch'),
        ),
    ]
