# Generated by Django 5.1.2 on 2024-10-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bank_branch_bank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
            preserve_default=False,
        ),
    ]
